DELETE FROM t_answers ; DELETE FROM t_questions; DELETE FROM t_users;
DELETE FROM t_psych_pref; DELETE FROM t_roles; DELETE FROM t_constraints;

INSERT INTO t_roles(role) VALUES
	('ROLE_ADMIN'),
	('ROLE_USER');

INSERT INTO t_constraints (minimum_value, maximum_value) 
	VALUES(-3, 3);

INSERT INTO t_psych_pref (code) 
	VALUES 
	('E'),
	('I'),
	('N'),
	('S'),
	('T'),
	('F'),
	('P'),
	('J');

INSERT INTO t_questions ("label", order_question, constraint_id, psych_pref_id)VALUES 
('Vous ressentez un besoin d''agir et d''interagir avec d''autres personnes pour vous ressourcer.', 1,
(SELECT id FROM t_constraints WHERE minimum_value = -3 AND maximum_value = 3), 
(SELECT id FROM t_psych_pref WHERE code = 'E')),
('Vous aimez être entouré de nombreuses personnes pendant votre temps libre.', 9,
(SELECT id FROM t_constraints WHERE minimum_value = -3 AND maximum_value = 3), 
(SELECT id FROM t_psych_pref WHERE code = 'E')), 
('Vous vous sentez bien quand vous êtes au centre de l''attention.', 17,
(SELECT id FROM t_constraints WHERE minimum_value = -3 AND maximum_value = 3), 
(SELECT id FROM t_psych_pref WHERE code = 'E')),
('Vous préférez discuter de vos idées avec d''autres personnes plutôt que de réfléchir seul.', 25, 
(SELECT id FROM t_constraints WHERE minimum_value = -3 AND maximum_value = 3), 
(SELECT id FROM t_psych_pref WHERE code = 'E')),
('Vous aimez rencontrer de nouvelles personnes et faire de nouvelles connaissances.', 33,
(SELECT id FROM t_constraints WHERE minimum_value = -3 AND maximum_value = 3), 
(SELECT id FROM t_psych_pref WHERE code = 'E')),
('Vous avez tendance à être dynamique et à chercher de nouvelles expériences.', 41, 
(SELECT id FROM t_constraints WHERE minimum_value = -3 AND maximum_value = 3), 
(SELECT id FROM t_psych_pref WHERE code = 'E')),
('Vous trouvez qu''un environnement social animé vous aide à rester motivé.', 49, 
(SELECT id FROM t_constraints WHERE minimum_value = -3 AND maximum_value = 3), 
(SELECT id FROM t_psych_pref WHERE code = 'E')),

('Vous préférez passer du temps seul pour vous ressourcer après une journée bien remplie.', 5, 
(SELECT id FROM t_constraints WHERE minimum_value = -3 AND maximum_value = 3), 
(SELECT id FROM t_psych_pref WHERE code = 'I')),
('Vous trouvez la solitude agréable et revigorante.', 13, 
(SELECT id FROM t_constraints WHERE minimum_value = -3 AND maximum_value = 3), 
(SELECT id FROM t_psych_pref WHERE code = 'I')),
('Vous vous sentez plus productif quand vous travaillez seul.', 21, 
(SELECT id FROM t_constraints WHERE minimum_value = -3 AND maximum_value = 3), 
(SELECT id FROM t_psych_pref WHERE code = 'I')),
('Lorsque vous avez des problèmes personnels, vous préférez y réfléchir seul plutôt que d''en parler à quelqu''un.', 29, 
(SELECT id FROM t_constraints WHERE minimum_value = -3 AND maximum_value = 3), 
(SELECT id FROM t_psych_pref WHERE code = 'I')),
('Vous êtes plus à l''aise dans des groupes restreints plutôt que dans de grands rassemblements sociaux.', 37, 
(SELECT id FROM t_constraints WHERE minimum_value = -3 AND maximum_value = 3), 
(SELECT id FROM t_psych_pref WHERE code = 'I')),
('Vous ressentez le besoin de moments calmes et réfléchis pour maintenir votre équilibre.', 45, 
(SELECT id FROM t_constraints WHERE minimum_value = -3 AND maximum_value = 3), 
(SELECT id FROM t_psych_pref WHERE code = 'I')),
('Vous préférez des interactions sociales moins fréquentes mais plus profondes.', 53, 
(SELECT id FROM t_constraints WHERE minimum_value = -3 AND maximum_value = 3), 
(SELECT id FROM t_psych_pref WHERE code = 'I')),

('Vous êtes attiré par des idées nouvelles et abstraites plutôt que par des faits concrets.', 2,
(SELECT id FROM t_constraints WHERE minimum_value = -3 AND maximum_value = 3), 
(SELECT id FROM t_psych_pref WHERE code = 'N')),
('Vous préférez réfléchir sur l''avenir plutôt que de vous concentrer sur le présent.', 10,
(SELECT id FROM t_constraints WHERE minimum_value = -3 AND maximum_value = 3), 
(SELECT id FROM t_psych_pref WHERE code = 'N')),
('Vous aimez discuter de concepts théoriques et de possibilités futures.', 18, 
(SELECT id FROM t_constraints WHERE minimum_value = -3 AND maximum_value = 3), 
(SELECT id FROM t_psych_pref WHERE code = 'N')),
('Vous avez une forte capacité à imaginer des solutions innovantes aux problèmes.', 26, 
(SELECT id FROM t_constraints WHERE minimum_value = -3 AND maximum_value = 3), 
(SELECT id FROM t_psych_pref WHERE code = 'N')),
('Vous trouvez souvent des liens ou des significations cachées dans les informations que vous recevez.', 34, 
(SELECT id FROM t_constraints WHERE minimum_value = -3 AND maximum_value = 3), 
(SELECT id FROM t_psych_pref WHERE code = 'N')),
('Vous aimez envisager plusieurs perspectives et possibilités avant de prendre une décision.', 42, 
(SELECT id FROM t_constraints WHERE minimum_value = -3 AND maximum_value = 3), 
(SELECT id FROM t_psych_pref WHERE code = 'N')),
('Vous préférez parfois changer d''approche si la situation semble plus prometteuse, même si cela peut sembler incertain.', 50, 
(SELECT id FROM t_constraints WHERE minimum_value = -3 AND maximum_value = 3), 
(SELECT id FROM t_psych_pref WHERE code = 'N')),

('Vous aimez vous concentrer sur des faits concrets et des informations tangibles.', 6, 
(SELECT id FROM t_constraints WHERE minimum_value = -3 AND maximum_value = 3), 
(SELECT id FROM t_psych_pref WHERE code = 'S')),
('Vous préférez des instructions détaillées et claires plutôt que des concepts flous.', 14, 
(SELECT id FROM t_constraints WHERE minimum_value = -3 AND maximum_value = 3), 
(SELECT id FROM t_psych_pref WHERE code = 'S')),
('Vous êtes plus à l''aise avec des méthodes pratiques et éprouvées que des idées théoriques.', 22, 
(SELECT id FROM t_constraints WHERE minimum_value = -3 AND maximum_value = 3), 
(SELECT id FROM t_psych_pref WHERE code = 'S')),
('Vous vous concentrez souvent sur les détails et appréciez une approche systématique.', 30, 
(SELECT id FROM t_constraints WHERE minimum_value = -3 AND maximum_value = 3), 
(SELECT id FROM t_psych_pref WHERE code = 'S')),
('Vous avez une préférence pour les activités pratiques qui nécessitent des actions concrètes.', 38, 
(SELECT id FROM t_constraints WHERE minimum_value = -3 AND maximum_value = 3), 
(SELECT id FROM t_psych_pref WHERE code = 'S')),
('Vous êtes plus attentif à ce qui se passe autour de vous plutôt qu''aux possibilités futures.', 46, 
(SELECT id FROM t_constraints WHERE minimum_value = -3 AND maximum_value = 3), 
(SELECT id FROM t_psych_pref WHERE code = 'S')),
('Vous vous sentez plus en sécurité lorsque vous avez des informations concrètes et vérifiables.', 54,
(SELECT id FROM t_constraints WHERE minimum_value = -3 AND maximum_value = 3), 
(SELECT id FROM t_psych_pref WHERE code = 'S')),

('Vous préférez prendre des décisions de manière logique et objective plutôt qu''émotionnelle.', 3,
(SELECT id FROM t_constraints WHERE minimum_value = -3 AND maximum_value = 3), 
(SELECT id FROM t_psych_pref WHERE code = 'T')),
('Vous vous concentrez sur l''analyse des faits pour résoudre un problème, même si cela peut sembler froid.', 11, 
(SELECT id FROM t_constraints WHERE minimum_value = -3 AND maximum_value = 3), 
(SELECT id FROM t_psych_pref WHERE code = 'T')),
('Vous êtes plus motivé par des résultats concrets que par des considérations émotionnelles.', 19, 
(SELECT id FROM t_constraints WHERE minimum_value = -3 AND maximum_value = 3), 
(SELECT id FROM t_psych_pref WHERE code = 'T')),
('Vous avez tendance à séparer vos sentiments des décisions professionnelles.', 27, 
(SELECT id FROM t_constraints WHERE minimum_value = -3 AND maximum_value = 3), 
(SELECT id FROM t_psych_pref WHERE code = 'T')),
('Vous appréciez un débat intellectuel où la logique prévaut sur les émotions.', 35, 
(SELECT id FROM t_constraints WHERE minimum_value = -3 AND maximum_value = 3), 
(SELECT id FROM t_psych_pref WHERE code = 'T')),
('Vous êtes plus à l''aise avec des discussions factuelles que personnelles.', 43, 
(SELECT id FROM t_constraints WHERE minimum_value = -3 AND maximum_value = 3), 
(SELECT id FROM t_psych_pref WHERE code = 'T')),
('Vous privilégiez l''efficacité et la rationalité dans vos choix.', 51, 
(SELECT id FROM t_constraints WHERE minimum_value = -3 AND maximum_value = 3), 
(SELECT id FROM t_psych_pref WHERE code = 'T')),

('Vous vous fiez davantage à vos émotions lorsque vous prenez des décisions.', 7, 
(SELECT id FROM t_constraints WHERE minimum_value = -3 AND maximum_value = 3), 
(SELECT id FROM t_psych_pref WHERE code = 'F')),
('Vous tenez compte des sentiments des autres lorsqu''il s''agit de prendre des décisions importantes.', 15, 
(SELECT id FROM t_constraints WHERE minimum_value = -3 AND maximum_value = 3), 
(SELECT id FROM t_psych_pref WHERE code = 'F')),
('Vous vous souciez de l''harmonie et de la compréhension dans vos relations interpersonnelles.', 23, 
(SELECT id FROM t_constraints WHERE minimum_value = -3 AND maximum_value = 3), 
(SELECT id FROM t_psych_pref WHERE code = 'F')),
('Vous appréciez un environnement où les émotions des autres sont respectées.', 31, 
(SELECT id FROM t_constraints WHERE minimum_value = -3 AND maximum_value = 3), 
(SELECT id FROM t_psych_pref WHERE code = 'F')),
('Vous prenez souvent en compte les valeurs humaines et les considérations éthiques dans vos décisions.', 39, 
(SELECT id FROM t_constraints WHERE minimum_value = -3 AND maximum_value = 3), 
(SELECT id FROM t_psych_pref WHERE code = 'F')),
('Vous préférez prendre des décisions qui sont perçues comme « justes » et équilibrées d''un point de vue humain.', 47, 
(SELECT id FROM t_constraints WHERE minimum_value = -3 AND maximum_value = 3), 
(SELECT id FROM t_psych_pref WHERE code = 'F')),
('Vous accordez de l''importance à la manière dont vos choix affectent le bien-être des autres.', 55, 
(SELECT id FROM t_constraints WHERE minimum_value = -3 AND maximum_value = 3), 
(SELECT id FROM t_psych_pref WHERE code = 'F')),

('Vous aimez garder vos options ouvertes au lieu de tout planifier à l''avance.', 4, 
(SELECT id FROM t_constraints WHERE minimum_value = -3 AND maximum_value = 3), 
(SELECT id FROM t_psych_pref WHERE code = 'P')),
('Vous préférez travailler de manière flexible et improvisée plutôt que d''avoir une structure rigide.', 12, 
(SELECT id FROM t_constraints WHERE minimum_value = -3 AND maximum_value = 3), 
(SELECT id FROM t_psych_pref WHERE code = 'P')),
('Vous aimez explorer de nouvelles possibilités plutôt que de suivre un plan préétabli.', 20, 
(SELECT id FROM t_constraints WHERE minimum_value = -3 AND maximum_value = 3), 
(SELECT id FROM t_psych_pref WHERE code = 'P')),
('Vous trouvez qu''il est difficile de vous engager dans des plans détaillés à long terme.', 28, 
(SELECT id FROM t_constraints WHERE minimum_value = -3 AND maximum_value = 3), 
(SELECT id FROM t_psych_pref WHERE code = 'P')),
('Vous vous sentez bien quand vous pouvez adapter votre emploi du temps à la situation.', 36, 
(SELECT id FROM t_constraints WHERE minimum_value = -3 AND maximum_value = 3), 
(SELECT id FROM t_psych_pref WHERE code = 'P')),
('Vous êtes plus motivé par les activités spontanées que par la prévision.', 44, 
(SELECT id FROM t_constraints WHERE minimum_value = -3 AND maximum_value = 3), 
(SELECT id FROM t_psych_pref WHERE code = 'P')),
('Vous avez tendance à laisser les choses se dérouler sans trop de planification.', 52, 
(SELECT id FROM t_constraints WHERE minimum_value = -3 AND maximum_value = 3), 
(SELECT id FROM t_psych_pref WHERE code = 'P')),

('Vous aimez avoir un plan et respecter un calendrier.', 8, 
(SELECT id FROM t_constraints WHERE minimum_value = -3 AND maximum_value = 3), 
(SELECT id FROM t_psych_pref WHERE code = 'J')),
('Vous vous sentez plus à l''aise lorsque vous avez tout organisé à l''avance.', 16, 
(SELECT id FROM t_constraints WHERE minimum_value = -3 AND maximum_value = 3), 
(SELECT id FROM t_psych_pref WHERE code = 'J')),
('Vous préférez terminer les tâches à temps et de manière structurée.', 24, 
(SELECT id FROM t_constraints WHERE minimum_value = -3 AND maximum_value = 3), 
(SELECT id FROM t_psych_pref WHERE code = 'J')),
('Vous vous concentrez sur les détails et les étapes de votre travail pour le mener à bien.', 32, 
(SELECT id FROM t_constraints WHERE minimum_value = -3 AND maximum_value = 3), 
(SELECT id FROM t_psych_pref WHERE code = 'J')),
('Vous aimez suivre un emploi du temps fixe plutôt que de laisser les choses se faire au jour le jour.', 40, 
(SELECT id FROM t_constraints WHERE minimum_value = -3 AND maximum_value = 3), 
(SELECT id FROM t_psych_pref WHERE code = 'J')),
('Vous avez un sens de l''urgence quand il s''agit de respecter les délais.', 48, 
(SELECT id FROM t_constraints WHERE minimum_value = -3 AND maximum_value = 3), 
(SELECT id FROM t_psych_pref WHERE code = 'J')),
('Vous aimez travailler avec des objectifs clairs et des échéances définies.', 56, 
(SELECT id FROM t_constraints WHERE minimum_value = -3 AND maximum_value = 3), 
(SELECT id FROM t_psych_pref WHERE code = 'J'))
;

SELECT * FROM t_psych_pref tpp;
SELECT * FROM t_constraints tc ;
SELECT * FROM t_roles tr; 
SELECT * FROM t_questions tq ;