DELETE FROM t_matches;
DELETE FROM t_mbti_types ;
DELETE FROM t_professions ;

INSERT INTO t_mbti_types (code, name, description, population_percentage, interesting_fact, image) VALUES 
	('ISTJ', 'Le Logisticien',
	'Les ISTJ sont des personnes disciplinées et fiables, attachées aux traditions et aux règles, qui s’assurent que chaque détail est pris en compte et que tout est fait dans les règles.',
	11.6, 
	'C''est le type de personnalité le plus représenté parmi les comptables et les militaires.',
	'ISTJ.webp'),
	
	('ISFJ', 'Le Défenseur',
	'Les ISFJ sont des protecteurs chaleureux et loyaux, profondément dévoués à leurs proches et toujours prêts à faire passer le bien-être des autres avant le leur.',
	13.7, 
	'Beaucoup d''infirmiers et de travailleurs sociaux sont ISFJ en raison de leur nature protectrice.',
	'ISFJ.webp'),

	('INFJ', 'L''Avocat', 
	'Les INFJ sont des idéalistes calmes et passionnés, animés par une grande empathie et de fortes valeurs, déterminés à guider et inspirer les autres pour un monde meilleur.',
	1.5,
	'C''est le type le plus rare de tous, ne représentant qu''environ 1,5 % de la population.',
	'INFJ.webp'),
	
	('INTJ', 'L''Architecte',
	'Les INTJ sont des penseurs stratégiques et indépendants, axés sur l’efficacité et la réalisation d’objectifs ambitieux.',
	2.1,
	'Beaucoup de chefs d’entreprise et de stratèges sont INTJ, notamment Elon Musk.',
	'INTJ.webp'),
	
	('ISTP', 'Le Virtuose',
	'Les ISTP sont des individus pragmatiques, ingénieux et réservés, à l’aise avec la mécanique et la résolution de problèmes concrets, abordant le monde comme un terrain d’expérimentation.',
	5.4,
	'Ce type est surreprésenté chez les ingénieurs et les artisans, appréciant les solutions pratiques.',
	'ISTP.webp'),
	
	('ISFP', 'L''Aventurier',
	'Les ISFP sont des esprits libres et artistiques, sensibles et spontanés, qui suivent leur cœur et recherchent sans cesse de nouvelles expériences.',
	8.8,
	'De nombreux artistes et designers sont ISFP, ce qui correspond à leur nature expressive.',
	'ISFP.webp'),
	
	('INFP', 'Le Médiateur',
	'Les INFP sont des âmes poétiques et bienveillantes, guidées par un riche monde intérieur et de profondes valeurs, toujours prêtes à soutenir les autres et à défendre des causes qui leur tiennent à cœur.',
	4.4,
	'J.R.R. Tolkien, auteur du Seigneur des Anneaux, est souvent cité comme un INFP typique.',
	'INFP.webp'),
	
	('INTP', 'Le Logicien',
	'Les INTP sont des esprits analytiques et novateurs, animés par une curiosité insatiable et le désir de tout comprendre de manière logique.',
	3.3,
	'C''est l''un des types les plus communs chez les philosophes et les programmeurs',
	'INTP.webp'),
	
	('ESTP', 'L''Entrepreneur',
	'Les ESTP sont des fonceurs vifs et audacieux, qui adorent l’action et le risque, vivant volontiers sur le fil du rasoir pour saisir chaque opportunité.',
	4.3,
	'James Bond est souvent cité comme un parfait exemple d’ESTP, audacieux et opportuniste.',
	'ESTP.webp'),
	
	('ESFP', 'L''Amuseur',
	'Les ESFP sont des personnes joviales et extraverties, spontanées et pleines d’énergie, avec qui on ne s’ennuie jamais.',
	8.5,
	'Ils sont souvent sous les projecteurs, qu''il s''agisse d''acteurs, musiciens ou influenceurs.',
	'ESFP.webp'),
	
	('ENFP', 'L''Inspirateur',
	'Les ENFP sont des explorateurs enthousiastes, débordants d’idées et de curiosité, cherchant toujours de nouvelles opportunités.',
	8.1,
	'Robin Williams était un ENFP classique, plein d’énergie et de créativité.',
	'ENFP.webp'),
	
	('ENTP', 'L''Innovateur',
	'Les ENTP sont des esprits astucieux et curieux, incapables de résister à un défi intellectuel.',
	3.2,
	'Ils adorent le débat et peuvent défendre une idée juste pour le plaisir de la discussion.',
	'ENTP.webp'),
	
	('ESTJ', 'Le Directeur',
	'Les ESTJ sont des organisateurs efficaces et pragmatiques, qui prennent naturellement les commandes et s’assurent que tout avance de manière ordonnée et productive.',
	8.7,
	'Ils sont souvent à la tête d’organisations, appréciant la structure et l’ordre.',
	'ESTJ.webp'),
	
	('ESFJ', 'Le Consul',
	'Les ESFJ sont des individus sociables et attentionnés, guidés par un profond sens de la communauté et du devoir, qui s’épanouissent en prenant soin des autres et en maintenant l’harmonie autour d’eux.',
	12.3,
	'C''est le type de personnalité le plus courant parmi les enseignants et hôtes d’événements.',
	'ESFJ.webp'),
	
	('ENFJ', 'Le Protagoniste',
	'Les ENFJ sont des meneurs charismatiques et empathiques, profondément altruistes, capables d’inspirer et de rassembler les autres autour d’une vision positive.',
	2.4,
	'Oprah Winfrey est souvent considérée comme un parfait exemple d’ENFJ, charismatique et inspirante.',
	'ENFJ.webp'),
	
	('ENTJ', 'Le Commandant',
	'Les ENTJ sont des leaders nés, ambitieux et déterminés, qui n’hésitent pas à imposer leur vision et à organiser efficacement les autres pour atteindre leurs objectifs audacieux.',
	1.8,
	'C''est le type le plus représenté chez les PDG et les stratèges politiques.',
	'ENTJ.webp');
	
INSERT INTO t_professions (name) VALUES
('Acteur'),
('Administrateur réseau'),
('Agent des forces spéciales'),
('Agent immobilier'),
('Agent sportif'),
('Analyste en conformité'),
('Analyste en criminalistique'),
('Analyste en géopolitique'),
('Analyste en R&D'),
('Analyste fiscal'),
('Analyste financier'),
('Analyste politique'),
('Animateur 2D/3D'),
('Animateur culturel'),
('Animateur de festivals'),
('Animateur radio'),
('Animateur social'),
('Animateur télé'),
('Architecte logiciel'),
('Architecte réseau'),
('Archiviste'),
('Archiviste médical'),
('Artiste plasticien'),
('Assistant de direction'),
('Assistant juridique'),
('Assistant social'),
('Auteur'),
('Avocat en droit de la tech'),
('Avocat en droit des affaires'),
('Bijoutier artisan'),
('Chargé d’affaires publiques'),
('Chargé de communication'),
('Chef de projet'),
('Chef de projet humanitaire'),
('Chef de projet IT'),
('Chercheur en intelligence artificielle'),
('Chercheur en neuroscience'),
('Chercheur scientifique'),
('Chanteur'),
('Coach bien-être'),
('Coach en créativité'),
('Coach en leadership'),
('Coach sportif'),
('Coach de vie'),
('Comptable'),
('Compositeur'),
('Conférencier en entrepreneuriat'),
('Conférencier motivationnel'),
('Concepteur de jeux vidéo'),
('Concepteur de mode'),
('Concepteur d’univers fictionnels'),
('Conseiller en politique sociale'),
('Consultant en bien-être au travail'),
('Consultant en communication'),
('Consultant en design thinking'),
('Consultant en développement personnel'),
('Consultant en éthique IA'),
('Consultant en gestion des risques'),
('Consultant en gestion de crise'),
('Consultant en image'),
('Consultant en innovation'),
('Consultant en marketing digital'),
('Consultant en organisation'),
('Consultant en relations internationales'),
('Consultant en relations publiques'),
('Consultant en ressources humaines'),
('Consultant en storytelling'),
('Consultant en stratégie d''entreprise'),
('Consultant en transformation digitale'),
('Contrôleur de gestion'),
('Coordinateur éducatif'),
('Cryptographe'),
('Danseur professionnel'),
('Data scientist'),
('Designer d’intérieur'),
('Développeur d''algorithmes'),
('Développeur en intelligence artificielle'),
('Développeur Full Stack'),
('Développeur indépendant'),
('Développeur Web créatif'),
('Développeur de logiciels embarqués'),
('Directeur RH'),
('Directeur R&D'),
('Directeur administratif'),
('Directeur commercial'),
('Directeur d’entreprise'),
('Directeur d’ONG'),
('Directeur de banque'),
('Directeur de banque d’investissement'),
('Directeur des opérations'),
('Directeur des systèmes d''information (DSI)'),
('Directeur d’usine'),
('Directeur financier'),
('Directeur marketing'),
('Designer UX/UI'),
('Designer de systèmes'),
('Designer graphique'),
('Économiste'),
('Écrivain'),
('Enquêteur scientifique'),
('Enseignant'),
('Enseignant-chercheur'),
('Entrepreneur'),
('Entrepreneur technologique'),
('Expert en cybersécurité'),
('Expert en marketing digital'),
('Fondateur de start-up'),
('Formateur en entreprise'),
('Formateur en santé publique'),
('Formateur en techniques de vente'),
('Game Designer'),
('Gestionnaire de carrière'),
('Gestionnaire immobilier'),
('Growth hacker'),
('Humanitaire'),
('Humoriste'),
('Illustrateur'),
('Infirmier'),
('Influenceur digital'),
('Ingénieur IA'),
('Ingénieur commercial'),
('Ingénieur en IA'),
('Ingénieur en automation'),
('Ingénieur en cybersécurité'),
('Ingénieur en développement durable'),
('Ingénieur en machine learning'),
('Ingénieur en mécanique'),
('Ingénieur en qualité'),
('Ingénieur en robotique'),
('Ingénieur en sûreté industrielle'),
('Ingénieur en systèmes embarqués'),
('Ingénieur industriel'),
('Ingénieur logiciel'),
('Juge'),
('Journaliste d’investigation'),
('Journaliste freelance'),
('Luthier'),
('Maître de cérémonie'),
('Mathématicien appliqué'),
('Mécanicien aéronautique'),
('Médiateur'),
('Médecin généraliste'),
('Musicien'),
('Négociateur en affaires'),
('Officier militaire'),
('Officier supérieur'),
('Orateur public'),
('PDG'),
('Philosophe académique'),
('Photographe'),
('Physicien'),
('Pilote d’essai'),
('Poète'),
('Policier'),
('Producteur audiovisuel'),
('Producteur de contenus numériques'),
('Professeur des écoles'),
('Professeur en arts'),
('Professeur en développement personnel'),
('Professeur en droit'),
('Professeur en entrepreneuriat'),
('Professeur en gestion d''entreprise'),
('Professeur en médias numériques'),
('Professeur en sciences humaines'),
('Professeur universitaire'),
('Programmeur scientifique'),
('Psychologue'),
('Psychologue du travail'),
('Rédacteur publicitaire'),
('Rédacteur web'),
('Responsable RH'),
('Responsable achats'),
('Responsable cybersécurité'),
('Responsable clientèle'),
('Responsable communication interne'),
('Responsable d’audit'),
('Responsable d’association'),
('Responsable d’événements'),
('Responsable diversité & inclusion'),
('Responsable engagement social'),
('Responsable événementiel'),
('Responsable formation'),
('Responsable innovation'),
('Responsable logistique'),
('Responsable marketing'),
('Responsable produit'),
('Responsable production'),
('Responsable relations presse'),
('Responsable service client'),
('Responsable service public'),
('Responsable des finances'),
('Responsable des ventes'),
('Responsable de casting'),
('Responsable de festival culturel'),
('Responsable de projets sociaux'),
('Scénariste'),
('Scénographe'),
('Spécialiste en accessibilité numérique'),
('Spécialiste en accompagnement scolaire'),
('Spécialiste en blockchain'),
('Spécialiste en communication de crise'),
('Spécialiste en communication non-violente'),
('Spécialiste en électronique automobile'),
('Spécialiste en expérience utilisateur'),
('Spécialiste en gamification'),
('Spécialiste en hacking éthique'),
('Spécialiste en intelligence économique'),
('Spécialiste en organisation d’événements'),
('Spécialiste en relations publiques'),
('Spécialiste en storytelling'),
('Spécialiste en transformation digitale'),
('Stratège militaire'),
('Styliste'),
('Tatoueur'),
('Technicien en biomécanique'),
('Thérapeute'),
('Thérapeute artistique'),
('Thérapeute familial'),
('Trader'),
('Traducteur littéraire');


INSERT INTO t_matches(mbti_type_id, profession_id)VALUES  
((SELECT id FROM t_mbti_types WHERE code = 'INTJ'), 
(SELECT id FROM t_professions WHERE name ='Chercheur scientifique')),
((SELECT id FROM t_mbti_types WHERE code = 'INTJ'), 
(SELECT id FROM t_professions WHERE name ='Analyste financier')),
((SELECT id FROM t_mbti_types WHERE code = 'INTJ'), 
(SELECT id FROM t_professions WHERE name ='Ingénieur en IA')),
((SELECT id FROM t_mbti_types WHERE code = 'INTJ'), 
(SELECT id FROM t_professions WHERE name ='Consultant en stratégie d''entreprise')),
((SELECT id FROM t_mbti_types WHERE code = 'INTJ'), 
(SELECT id FROM t_professions WHERE name ='Directeur R&D')),
((SELECT id FROM t_mbti_types WHERE code = 'INTJ'), 
(SELECT id FROM t_professions WHERE name ='Avocat en droit des affaires')),
((SELECT id FROM t_mbti_types WHERE code = 'INTJ'), 
(SELECT id FROM t_professions WHERE name ='Architecte logiciel')),
((SELECT id FROM t_mbti_types WHERE code = 'INTJ'), 
(SELECT id FROM t_professions WHERE name ='Économiste')),
((SELECT id FROM t_mbti_types WHERE code = 'INTJ'), 
(SELECT id FROM t_professions WHERE name ='Responsable cybersécurité')),
((SELECT id FROM t_mbti_types WHERE code = 'INTJ'), 
(SELECT id FROM t_professions WHERE name = 'Spécialiste en intelligence économique')),
((SELECT id FROM t_mbti_types WHERE code = 'INTJ'), 
(SELECT id FROM t_professions WHERE name ='Professeur universitaire')),
((SELECT id FROM t_mbti_types WHERE code = 'INTJ'), 
(SELECT id FROM t_professions WHERE name ='Entrepreneur technologique')),
((SELECT id FROM t_mbti_types WHERE code = 'INTJ'), 
(SELECT id FROM t_professions WHERE name ='Chef de projet IT')),
((SELECT id FROM t_mbti_types WHERE code = 'INTJ'), 
(SELECT id FROM t_professions WHERE name ='Analyste en géopolitique')),
((SELECT id FROM t_mbti_types WHERE code = 'INTJ'), 
(SELECT id FROM t_professions WHERE name ='Ingénieur en automation'));

INSERT INTO t_matches(mbti_type_id, profession_id)VALUES   
((SELECT id FROM t_mbti_types WHERE code = 'INTP'),
(SELECT id FROM t_professions WHERE name = 'Physicien')),
((SELECT id FROM t_mbti_types WHERE code = 'INTP'),
(SELECT id FROM t_professions WHERE name = 'Développeur d''algorithmes')),
((SELECT id FROM t_mbti_types WHERE code = 'INTP'),
(SELECT id FROM t_professions WHERE name = 'Mathématicien appliqué')),
((SELECT id FROM t_mbti_types WHERE code = 'INTP'),
(SELECT id FROM t_professions WHERE name = 'Expert en cybersécurité')),
((SELECT id FROM t_mbti_types WHERE code = 'INTP'),
(SELECT id FROM t_professions WHERE name = 'Spécialiste en blockchain')),
((SELECT id FROM t_mbti_types WHERE code = 'INTP'),
(SELECT id FROM t_professions WHERE name = 'Philosophe académique')),
((SELECT id FROM t_mbti_types WHERE code = 'INTP'),
(SELECT id FROM t_professions WHERE name = 'Chercheur en intelligence artificielle')),
((SELECT id FROM t_mbti_types WHERE code = 'INTP'),
(SELECT id FROM t_professions WHERE name = 'Analyste en R&D')),
((SELECT id FROM t_mbti_types WHERE code = 'INTP'),
(SELECT id FROM t_professions WHERE name = 'Programmeur scientifique')),
((SELECT id FROM t_mbti_types WHERE code = 'INTP'),
(SELECT id FROM t_professions WHERE name = 'Designer de systèmes')),
((SELECT id FROM t_mbti_types WHERE code = 'INTP'),
(SELECT id FROM t_professions WHERE name = 'Data scientist')),
((SELECT id FROM t_mbti_types WHERE code = 'INTP'),
(SELECT id FROM t_professions WHERE name = 'Consultant en innovation')),
((SELECT id FROM t_mbti_types WHERE code = 'INTP'),
(SELECT id FROM t_professions WHERE name = 'Enseignant-chercheur')),
((SELECT id FROM t_mbti_types WHERE code = 'INTP'),
(SELECT id FROM t_professions WHERE name = 'Ingénieur en machine learning')),
((SELECT id FROM t_mbti_types WHERE code = 'INTP'),
(SELECT id FROM t_professions WHERE name = 'Cryptographe'));

INSERT INTO t_matches(mbti_type_id, profession_id)VALUES   
((SELECT id FROM t_mbti_types WHERE code = 'ENTJ'),
(SELECT id FROM t_professions WHERE name = 'PDG')),
((SELECT id FROM t_mbti_types WHERE code = 'ENTJ'),
(SELECT id FROM t_professions WHERE name = 'Directeur des opérations')),
((SELECT id FROM t_mbti_types WHERE code = 'ENTJ'),
(SELECT id FROM t_professions WHERE name = 'Responsable marketing')),
((SELECT id FROM t_mbti_types WHERE code = 'ENTJ'),
(SELECT id FROM t_professions WHERE name = 'Ingénieur industriel')),
((SELECT id FROM t_mbti_types WHERE code = 'ENTJ'),
(SELECT id FROM t_professions WHERE name = 'Consultant en transformation digitale')),
((SELECT id FROM t_mbti_types WHERE code = 'ENTJ'),
(SELECT id FROM t_professions WHERE name = 'Directeur des systèmes d''information (DSI)')),
((SELECT id FROM t_mbti_types WHERE code = 'ENTJ'),
(SELECT id FROM t_professions WHERE name = 'Stratège militaire')),
((SELECT id FROM t_mbti_types WHERE code = 'ENTJ'),
(SELECT id FROM t_professions WHERE name = 'Analyste politique')),
((SELECT id FROM t_mbti_types WHERE code = 'ENTJ'),
(SELECT id FROM t_professions WHERE name = 'Responsable produit')),
((SELECT id FROM t_mbti_types WHERE code = 'ENTJ'),
(SELECT id FROM t_professions WHERE name = 'Directeur de banque d’investissement')),
((SELECT id FROM t_mbti_types WHERE code = 'ENTJ'),
(SELECT id FROM t_professions WHERE name = 'Ingénieur en développement durable')),
((SELECT id FROM t_mbti_types WHERE code = 'ENTJ'),
(SELECT id FROM t_professions WHERE name = 'Responsable innovation')),
((SELECT id FROM t_mbti_types WHERE code = 'ENTJ'),
(SELECT id FROM t_professions WHERE name = 'Entrepreneur')),
((SELECT id FROM t_mbti_types WHERE code = 'ENTJ'),
(SELECT id FROM t_professions WHERE name = 'Chef de projet IT')),
((SELECT id FROM t_mbti_types WHERE code = 'ENTJ'),
(SELECT id FROM t_professions WHERE name = 'Professeur en gestion d''entreprise'));

INSERT INTO t_matches(mbti_type_id, profession_id)VALUES   
((SELECT id FROM t_mbti_types WHERE code = 'ENTP'),
(SELECT id FROM t_professions WHERE name = 'Journaliste d’investigation')),
((SELECT id FROM t_mbti_types WHERE code = 'ENTP'),
(SELECT id FROM t_professions WHERE name = 'Producteur audiovisuel')),
((SELECT id FROM t_mbti_types WHERE code = 'ENTP'),
(SELECT id FROM t_professions WHERE name = 'Consultant en innovation')),
((SELECT id FROM t_mbti_types WHERE code = 'ENTP'),
(SELECT id FROM t_professions WHERE name = 'Expert en marketing digital')),
((SELECT id FROM t_mbti_types WHERE code = 'ENTP'),
(SELECT id FROM t_professions WHERE name = 'Ingénieur en robotique')),
((SELECT id FROM t_mbti_types WHERE code = 'ENTP'),
(SELECT id FROM t_professions WHERE name = 'Avocat en droit de la tech')),
((SELECT id FROM t_mbti_types WHERE code = 'ENTP'),
(SELECT id FROM t_professions WHERE name = 'Conférencier en entrepreneuriat')),
((SELECT id FROM t_mbti_types WHERE code = 'ENTP'),
(SELECT id FROM t_professions WHERE name = 'Chercheur en neuroscience')),
((SELECT id FROM t_mbti_types WHERE code = 'ENTP'),
(SELECT id FROM t_professions WHERE name = 'Ingénieur en IA')),
((SELECT id FROM t_mbti_types WHERE code = 'ENTP'),
(SELECT id FROM t_professions WHERE name = 'Développeur Full Stack')),
((SELECT id FROM t_mbti_types WHERE code = 'ENTP'),
(SELECT id FROM t_professions WHERE name = 'Fondateur de start-up')),
((SELECT id FROM t_mbti_types WHERE code = 'ENTP'),
(SELECT id FROM t_professions WHERE name = 'Concepteur de jeux vidéo')),
((SELECT id FROM t_mbti_types WHERE code = 'ENTP'),
(SELECT id FROM t_professions WHERE name = 'Spécialiste en gamification')),
((SELECT id FROM t_mbti_types WHERE code = 'ENTP'),
(SELECT id FROM t_professions WHERE name = 'Growth hacker')),
((SELECT id FROM t_mbti_types WHERE code = 'ENTP'),
(SELECT id FROM t_professions WHERE name = 'Professeur en entrepreneuriat'));

INSERT INTO t_matches(mbti_type_id, profession_id)VALUES   
((SELECT id FROM t_mbti_types WHERE code = 'INFJ'),
(SELECT id FROM t_professions WHERE name = 'Psychologue')),
((SELECT id FROM t_mbti_types WHERE code = 'INFJ'),
(SELECT id FROM t_professions WHERE name = 'Médiateur')),
((SELECT id FROM t_mbti_types WHERE code = 'INFJ'),
(SELECT id FROM t_professions WHERE name = 'Consultant en développement personnel')),
((SELECT id FROM t_mbti_types WHERE code = 'INFJ'),
(SELECT id FROM t_professions WHERE name = 'Coach de vie')),
((SELECT id FROM t_mbti_types WHERE code = 'INFJ'),
(SELECT id FROM t_professions WHERE name = 'Conseiller en politique sociale')),
((SELECT id FROM t_mbti_types WHERE code = 'INFJ'),
(SELECT id FROM t_professions WHERE name = 'Thérapeute familial')),
((SELECT id FROM t_mbti_types WHERE code = 'INFJ'),
(SELECT id FROM t_professions WHERE name = 'Philosophe académique')),
((SELECT id FROM t_mbti_types WHERE code = 'INFJ'),
(SELECT id FROM t_professions WHERE name = 'Auteur')),
((SELECT id FROM t_mbti_types WHERE code = 'INFJ'),
(SELECT id FROM t_professions WHERE name = 'Professeur en sciences humaines')),
((SELECT id FROM t_mbti_types WHERE code = 'INFJ'),
(SELECT id FROM t_professions WHERE name = 'Spécialiste en communication non-violente')),
((SELECT id FROM t_mbti_types WHERE code = 'INFJ'),
(SELECT id FROM t_professions WHERE name = 'Consultant en éthique IA')),
((SELECT id FROM t_mbti_types WHERE code = 'INFJ'),
(SELECT id FROM t_professions WHERE name = 'Humanitaire')),
((SELECT id FROM t_mbti_types WHERE code = 'INFJ'),
(SELECT id FROM t_professions WHERE name = 'Responsable diversité & inclusion')),
((SELECT id FROM t_mbti_types WHERE code = 'INFJ'),
(SELECT id FROM t_professions WHERE name = 'Consultant en relations internationales')),
((SELECT id FROM t_mbti_types WHERE code = 'INFJ'),
(SELECT id FROM t_professions WHERE name = 'Directeur d’ONG'));

INSERT INTO t_matches(mbti_type_id, profession_id)VALUES   
((SELECT id FROM t_mbti_types WHERE code = 'INFP'),
(SELECT id FROM t_professions WHERE name = 'Écrivain')),
((SELECT id FROM t_mbti_types WHERE code = 'INFP'),
(SELECT id FROM t_professions WHERE name = 'Poète')),
((SELECT id FROM t_mbti_types WHERE code = 'INFP'),
(SELECT id FROM t_professions WHERE name = 'Scénariste')),
((SELECT id FROM t_mbti_types WHERE code = 'INFP'),
(SELECT id FROM t_professions WHERE name = 'Illustrateur')),
((SELECT id FROM t_mbti_types WHERE code = 'INFP'),
(SELECT id FROM t_professions WHERE name = 'Compositeur')),
((SELECT id FROM t_mbti_types WHERE code = 'INFP'),
(SELECT id FROM t_professions WHERE name = 'Thérapeute artistique')),
((SELECT id FROM t_mbti_types WHERE code = 'INFP'),
(SELECT id FROM t_professions WHERE name = 'Game Designer')),
((SELECT id FROM t_mbti_types WHERE code = 'INFP'),
(SELECT id FROM t_professions WHERE name = 'Rédacteur web')),
((SELECT id FROM t_mbti_types WHERE code = 'INFP'),
(SELECT id FROM t_professions WHERE name = 'Développeur indépendant')),
((SELECT id FROM t_mbti_types WHERE code = 'INFP'),
(SELECT id FROM t_professions WHERE name = 'Consultant en storytelling')),
((SELECT id FROM t_mbti_types WHERE code = 'INFP'),
(SELECT id FROM t_professions WHERE name = 'Professeur en arts')),
((SELECT id FROM t_mbti_types WHERE code = 'INFP'),
(SELECT id FROM t_professions WHERE name = 'Philosophe académique')),
((SELECT id FROM t_mbti_types WHERE code = 'INFP'),
(SELECT id FROM t_professions WHERE name = 'Traducteur littéraire')),
((SELECT id FROM t_mbti_types WHERE code = 'INFP'),
(SELECT id FROM t_professions WHERE name = 'Concepteur d’univers fictionnels')),
((SELECT id FROM t_mbti_types WHERE code = 'INFP'),
(SELECT id FROM t_professions WHERE name = 'Animateur culturel'));

INSERT INTO t_matches(mbti_type_id, profession_id)VALUES   
((SELECT id FROM t_mbti_types WHERE code = 'ENFJ'),
(SELECT id FROM t_professions WHERE name = 'Enseignant')),
((SELECT id FROM t_mbti_types WHERE code = 'ENFJ'),
(SELECT id FROM t_professions WHERE name = 'Coach en leadership')),
((SELECT id FROM t_mbti_types WHERE code = 'ENFJ'),
(SELECT id FROM t_professions WHERE name = 'Consultant en communication')),
((SELECT id FROM t_mbti_types WHERE code = 'ENFJ'),
(SELECT id FROM t_professions WHERE name = 'Directeur RH')),
((SELECT id FROM t_mbti_types WHERE code = 'ENFJ'),
(SELECT id FROM t_professions WHERE name = 'Responsable engagement social')),
((SELECT id FROM t_mbti_types WHERE code = 'ENFJ'),
(SELECT id FROM t_professions WHERE name = 'Orateur public')),
((SELECT id FROM t_mbti_types WHERE code = 'ENFJ'),
(SELECT id FROM t_professions WHERE name = 'Formateur en entreprise')),
((SELECT id FROM t_mbti_types WHERE code = 'ENFJ'),
(SELECT id FROM t_professions WHERE name = 'Chef de projet humanitaire')),
((SELECT id FROM t_mbti_types WHERE code = 'ENFJ'),
(SELECT id FROM t_professions WHERE name = 'Responsable événementiel')),
((SELECT id FROM t_mbti_types WHERE code = 'ENFJ'),
(SELECT id FROM t_professions WHERE name = 'Psychologue du travail')),
((SELECT id FROM t_mbti_types WHERE code = 'ENFJ'),
(SELECT id FROM t_professions WHERE name = 'Auteur')),
((SELECT id FROM t_mbti_types WHERE code = 'ENFJ'),
(SELECT id FROM t_professions WHERE name = 'Responsable marketing')),
((SELECT id FROM t_mbti_types WHERE code = 'ENFJ'),
(SELECT id FROM t_professions WHERE name = 'Professeur en développement personnel')),
((SELECT id FROM t_mbti_types WHERE code = 'ENFJ'),
(SELECT id FROM t_professions WHERE name = 'Consultant en relations publiques')),
((SELECT id FROM t_mbti_types WHERE code = 'ENFJ'),
(SELECT id FROM t_professions WHERE name = 'Responsable formation'));

INSERT INTO t_matches(mbti_type_id, profession_id)VALUES   
((SELECT id FROM t_mbti_types WHERE code = 'ENFP'),
(SELECT id FROM t_professions WHERE name = 'Animateur radio')),
((SELECT id FROM t_mbti_types WHERE code = 'ENFP'),
(SELECT id FROM t_professions WHERE name = 'Influenceur digital')),
((SELECT id FROM t_mbti_types WHERE code = 'ENFP'),
(SELECT id FROM t_professions WHERE name = 'Consultant en innovation')),
((SELECT id FROM t_mbti_types WHERE code = 'ENFP'),
(SELECT id FROM t_professions WHERE name = 'Producteur de contenus numériques')),
((SELECT id FROM t_mbti_types WHERE code = 'ENFP'),
(SELECT id FROM t_professions WHERE name = 'Journaliste freelance')),
((SELECT id FROM t_mbti_types WHERE code = 'ENFP'),
(SELECT id FROM t_professions WHERE name = 'Fondateur de start-up')),
((SELECT id FROM t_mbti_types WHERE code = 'ENFP'),
(SELECT id FROM t_professions WHERE name = 'Conférencier motivationnel')),
((SELECT id FROM t_mbti_types WHERE code = 'ENFP'),
(SELECT id FROM t_professions WHERE name = 'Scénariste')),
((SELECT id FROM t_mbti_types WHERE code = 'ENFP'),
(SELECT id FROM t_professions WHERE name = 'Consultant en design thinking')),
((SELECT id FROM t_mbti_types WHERE code = 'ENFP'),
(SELECT id FROM t_professions WHERE name = 'Développeur Web créatif')),
((SELECT id FROM t_mbti_types WHERE code = 'ENFP'),
(SELECT id FROM t_professions WHERE name = 'Game Designer')),
((SELECT id FROM t_mbti_types WHERE code = 'ENFP'),
(SELECT id FROM t_professions WHERE name = 'Spécialiste en expérience utilisateur')),
((SELECT id FROM t_mbti_types WHERE code = 'ENFP'),
(SELECT id FROM t_professions WHERE name = 'Responsable de festival culturel')),
((SELECT id FROM t_mbti_types WHERE code = 'ENFP'),
(SELECT id FROM t_professions WHERE name = 'Coach en créativité')),
((SELECT id FROM t_mbti_types WHERE code = 'ENFP'),
(SELECT id FROM t_professions WHERE name = 'Professeur en médias numériques'));

INSERT INTO t_matches(mbti_type_id, profession_id)VALUES   
((SELECT id FROM t_mbti_types WHERE code = 'ISTJ'),
(SELECT id FROM t_professions WHERE name = 'Comptable')),
((SELECT id FROM t_mbti_types WHERE code = 'ISTJ'),
(SELECT id FROM t_professions WHERE name = 'Juge')),
((SELECT id FROM t_mbti_types WHERE code = 'ISTJ'),
(SELECT id FROM t_professions WHERE name = 'Policier')),
((SELECT id FROM t_mbti_types WHERE code = 'ISTJ'),
(SELECT id FROM t_professions WHERE name = 'Administrateur réseau')),
((SELECT id FROM t_mbti_types WHERE code = 'ISTJ'),
(SELECT id FROM t_professions WHERE name = 'Responsable des finances')),
((SELECT id FROM t_mbti_types WHERE code = 'ISTJ'),
(SELECT id FROM t_professions WHERE name = 'Contrôleur de gestion')),
((SELECT id FROM t_mbti_types WHERE code = 'ISTJ'),
(SELECT id FROM t_professions WHERE name = 'Ingénieur en qualité')),
((SELECT id FROM t_mbti_types WHERE code = 'ISTJ'),
(SELECT id FROM t_professions WHERE name = 'Archiviste')),
((SELECT id FROM t_mbti_types WHERE code = 'ISTJ'),
(SELECT id FROM t_professions WHERE name = 'Responsable logistique')),
((SELECT id FROM t_mbti_types WHERE code = 'ISTJ'),
(SELECT id FROM t_professions WHERE name = 'Analyste en conformité')),
((SELECT id FROM t_mbti_types WHERE code = 'ISTJ'),
(SELECT id FROM t_professions WHERE name = 'Officier militaire')),
((SELECT id FROM t_mbti_types WHERE code = 'ISTJ'),
(SELECT id FROM t_professions WHERE name = 'Analyste fiscal')),
((SELECT id FROM t_mbti_types WHERE code = 'ISTJ'),
(SELECT id FROM t_professions WHERE name = 'Professeur en droit')),
((SELECT id FROM t_mbti_types WHERE code = 'ISTJ'),
(SELECT id FROM t_professions WHERE name = 'Ingénieur en sûreté industrielle')),
((SELECT id FROM t_mbti_types WHERE code = 'ISTJ'),
(SELECT id FROM t_professions WHERE name = 'Consultant en gestion des risques'));

INSERT INTO t_matches(mbti_type_id, profession_id)VALUES   
((SELECT id FROM t_mbti_types WHERE code = 'ISFJ'),
(SELECT id FROM t_professions WHERE name = 'Infirmier')),
((SELECT id FROM t_mbti_types WHERE code = 'ISFJ'),
(SELECT id FROM t_professions WHERE name = 'Professeur des écoles')),
((SELECT id FROM t_mbti_types WHERE code = 'ISFJ'),
(SELECT id FROM t_professions WHERE name = 'Assistant social')),
((SELECT id FROM t_mbti_types WHERE code = 'ISFJ'),
(SELECT id FROM t_professions WHERE name = 'Médecin généraliste')),
((SELECT id FROM t_mbti_types WHERE code = 'ISFJ'),
(SELECT id FROM t_professions WHERE name = 'Responsable service client')),
((SELECT id FROM t_mbti_types WHERE code = 'ISFJ'),
(SELECT id FROM t_professions WHERE name = 'Archiviste médical')),
((SELECT id FROM t_mbti_types WHERE code = 'ISFJ'),
(SELECT id FROM t_professions WHERE name = 'Consultant en ressources humaines')),
((SELECT id FROM t_mbti_types WHERE code = 'ISFJ'),
(SELECT id FROM t_professions WHERE name = 'Chargé d’affaires publiques')),
((SELECT id FROM t_mbti_types WHERE code = 'ISFJ'),
(SELECT id FROM t_professions WHERE name = 'Responsable d’association')),
((SELECT id FROM t_mbti_types WHERE code = 'ISFJ'),
(SELECT id FROM t_professions WHERE name = 'Thérapeute')),
((SELECT id FROM t_mbti_types WHERE code = 'ISFJ'),
(SELECT id FROM t_professions WHERE name = 'Spécialiste en accessibilité numérique')),
((SELECT id FROM t_mbti_types WHERE code = 'ISFJ'),
(SELECT id FROM t_professions WHERE name = 'Coordinateur éducatif')),
((SELECT id FROM t_mbti_types WHERE code = 'ISFJ'),
(SELECT id FROM t_professions WHERE name = 'Responsable communication interne')),
((SELECT id FROM t_mbti_types WHERE code = 'ISFJ'),
(SELECT id FROM t_professions WHERE name = 'Formateur en santé publique')),
((SELECT id FROM t_mbti_types WHERE code = 'ISFJ'),
(SELECT id FROM t_professions WHERE name = 'Assistant juridique'));

INSERT INTO t_matches(mbti_type_id, profession_id)VALUES   
((SELECT id FROM t_mbti_types WHERE code = 'ESTJ'),
(SELECT id FROM t_professions WHERE name = 'Directeur d’entreprise')),
((SELECT id FROM t_mbti_types WHERE code = 'ESTJ'),
(SELECT id FROM t_professions WHERE name = 'Chef de projet')),
((SELECT id FROM t_mbti_types WHERE code = 'ESTJ'),
(SELECT id FROM t_professions WHERE name = 'Directeur des opérations')),
((SELECT id FROM t_mbti_types WHERE code = 'ESTJ'),
(SELECT id FROM t_professions WHERE name = 'Officier supérieur')),
((SELECT id FROM t_mbti_types WHERE code = 'ESTJ'),
(SELECT id FROM t_professions WHERE name = 'Directeur commercial')),
((SELECT id FROM t_mbti_types WHERE code = 'ESTJ'),
(SELECT id FROM t_professions WHERE name = 'Responsable achats')),
((SELECT id FROM t_mbti_types WHERE code = 'ESTJ'),
(SELECT id FROM t_professions WHERE name = 'Responsable production')),
((SELECT id FROM t_mbti_types WHERE code = 'ESTJ'),
(SELECT id FROM t_professions WHERE name = 'Directeur administratif')),
((SELECT id FROM t_mbti_types WHERE code = 'ESTJ'),
(SELECT id FROM t_professions WHERE name = 'Directeur de banque')),
((SELECT id FROM t_mbti_types WHERE code = 'ESTJ'),
(SELECT id FROM t_professions WHERE name = 'Directeur d’usine')),
((SELECT id FROM t_mbti_types WHERE code = 'ESTJ'),
(SELECT id FROM t_professions WHERE name = 'Directeur financier')),
((SELECT id FROM t_mbti_types WHERE code = 'ESTJ'),
(SELECT id FROM t_professions WHERE name = 'Responsable d’audit')),
((SELECT id FROM t_mbti_types WHERE code = 'ESTJ'),
(SELECT id FROM t_professions WHERE name = 'Consultant en organisation')),
((SELECT id FROM t_mbti_types WHERE code = 'ESTJ'),
(SELECT id FROM t_professions WHERE name = 'Responsable service public')),
((SELECT id FROM t_mbti_types WHERE code = 'ESTJ'),
(SELECT id FROM t_professions WHERE name = 'Gestionnaire immobilier'));

INSERT INTO t_matches(mbti_type_id, profession_id)VALUES   
((SELECT id FROM t_mbti_types WHERE code = 'ESFJ'),
(SELECT id FROM t_professions WHERE name = 'Enseignant')),
((SELECT id FROM t_mbti_types WHERE code = 'ESFJ'),
(SELECT id FROM t_professions WHERE name = 'Responsable RH')),
((SELECT id FROM t_mbti_types WHERE code = 'ESFJ'),
(SELECT id FROM t_professions WHERE name = 'Chargé de communication')),
((SELECT id FROM t_mbti_types WHERE code = 'ESFJ'),
(SELECT id FROM t_professions WHERE name = 'Animateur social')),
((SELECT id FROM t_mbti_types WHERE code = 'ESFJ'),
(SELECT id FROM t_professions WHERE name = 'Responsable d’événements')),
((SELECT id FROM t_mbti_types WHERE code = 'ESFJ'),
(SELECT id FROM t_professions WHERE name = 'Directeur marketing')),
((SELECT id FROM t_mbti_types WHERE code = 'ESFJ'),
(SELECT id FROM t_professions WHERE name = 'Responsable clientèle')),
((SELECT id FROM t_mbti_types WHERE code = 'ESFJ'),
(SELECT id FROM t_professions WHERE name = 'Coach bien-être')),
((SELECT id FROM t_mbti_types WHERE code = 'ESFJ'),
(SELECT id FROM t_professions WHERE name = 'Infirmier')),
((SELECT id FROM t_mbti_types WHERE code = 'ESFJ'),
(SELECT id FROM t_professions WHERE name = 'Formateur en entreprise')),
((SELECT id FROM t_mbti_types WHERE code = 'ESFJ'),
(SELECT id FROM t_professions WHERE name = 'Consultant en bien-être au travail')),
((SELECT id FROM t_mbti_types WHERE code = 'ESFJ'),
(SELECT id FROM t_professions WHERE name = 'Responsable de projets sociaux')),
((SELECT id FROM t_mbti_types WHERE code = 'ESFJ'),
(SELECT id FROM t_professions WHERE name = 'Spécialiste en accompagnement scolaire')),
((SELECT id FROM t_mbti_types WHERE code = 'ESFJ'),
(SELECT id FROM t_professions WHERE name = 'Assistant de direction')),
((SELECT id FROM t_mbti_types WHERE code = 'ESFJ'),
(SELECT id FROM t_professions WHERE name = 'Gestionnaire de carrière'));

INSERT INTO t_matches(mbti_type_id, profession_id)VALUES   
((SELECT id FROM t_mbti_types WHERE code = 'ISTP'),
(SELECT id FROM t_professions WHERE name = 'Ingénieur en mécanique')),
((SELECT id FROM t_mbti_types WHERE code = 'ISTP'),
(SELECT id FROM t_professions WHERE name = 'Pilote d’essai')),
((SELECT id FROM t_mbti_types WHERE code = 'ISTP'),
(SELECT id FROM t_professions WHERE name = 'Enquêteur scientifique')),
((SELECT id FROM t_mbti_types WHERE code = 'ISTP'),
(SELECT id FROM t_professions WHERE name = 'Ingénieur en robotique')),
((SELECT id FROM t_mbti_types WHERE code = 'ISTP'),
(SELECT id FROM t_professions WHERE name = 'Mécanicien aéronautique')),
((SELECT id FROM t_mbti_types WHERE code = 'ISTP'),
(SELECT id FROM t_professions WHERE name = 'Développeur de logiciels embarqués')),
((SELECT id FROM t_mbti_types WHERE code = 'ISTP'),
(SELECT id FROM t_professions WHERE name = 'Analyste en criminalistique')),
((SELECT id FROM t_mbti_types WHERE code = 'ISTP'),
(SELECT id FROM t_professions WHERE name = 'Expert en cybersécurité')),
((SELECT id FROM t_mbti_types WHERE code = 'ISTP'),
(SELECT id FROM t_professions WHERE name = 'Spécialiste en électronique automobile')),
((SELECT id FROM t_mbti_types WHERE code = 'ISTP'),
(SELECT id FROM t_professions WHERE name = 'Technicien en biomécanique')),
((SELECT id FROM t_mbti_types WHERE code = 'ISTP'),
(SELECT id FROM t_professions WHERE name = 'Agent des forces spéciales')),
((SELECT id FROM t_mbti_types WHERE code = 'ISTP'),
(SELECT id FROM t_professions WHERE name = 'Ingénieur en systèmes embarqués')),
((SELECT id FROM t_mbti_types WHERE code = 'ISTP'),
(SELECT id FROM t_professions WHERE name = 'Développeur en intelligence artificielle')),
((SELECT id FROM t_mbti_types WHERE code = 'ISTP'),
(SELECT id FROM t_professions WHERE name = 'Spécialiste en hacking éthique')),
((SELECT id FROM t_mbti_types WHERE code = 'ISTP'),
(SELECT id FROM t_professions WHERE name = 'Architecte réseau'));

INSERT INTO t_matches(mbti_type_id, profession_id)VALUES   
((SELECT id FROM t_mbti_types WHERE code = 'ISFP'),
(SELECT id FROM t_professions WHERE name = 'Designer graphique')),
((SELECT id FROM t_mbti_types WHERE code = 'ISFP'),
(SELECT id FROM t_professions WHERE name = 'Tatoueur')),
((SELECT id FROM t_mbti_types WHERE code = 'ISFP'),
(SELECT id FROM t_professions WHERE name = 'Styliste')),
((SELECT id FROM t_mbti_types WHERE code = 'ISFP'),
(SELECT id FROM t_professions WHERE name = 'Illustrateur')),
((SELECT id FROM t_mbti_types WHERE code = 'ISFP'),
(SELECT id FROM t_professions WHERE name = 'Photographe')),
((SELECT id FROM t_mbti_types WHERE code = 'ISFP'),
(SELECT id FROM t_professions WHERE name = 'Artiste plasticien')),
((SELECT id FROM t_mbti_types WHERE code = 'ISFP'),
(SELECT id FROM t_professions WHERE name = 'Luthier')),
((SELECT id FROM t_mbti_types WHERE code = 'ISFP'),
(SELECT id FROM t_professions WHERE name = 'Concepteur de mode')),
((SELECT id FROM t_mbti_types WHERE code = 'ISFP'),
(SELECT id FROM t_professions WHERE name = 'Animateur 2D/3D')),
((SELECT id FROM t_mbti_types WHERE code = 'ISFP'),
(SELECT id FROM t_professions WHERE name = 'Designer d’intérieur')),
((SELECT id FROM t_mbti_types WHERE code = 'ISFP'),
(SELECT id FROM t_professions WHERE name = 'Bijoutier artisan')),
((SELECT id FROM t_mbti_types WHERE code = 'ISFP'),
(SELECT id FROM t_professions WHERE name = 'Scénographe')),
((SELECT id FROM t_mbti_types WHERE code = 'ISFP'),
(SELECT id FROM t_professions WHERE name = 'Rédacteur publicitaire')),
((SELECT id FROM t_mbti_types WHERE code = 'ISFP'),
(SELECT id FROM t_professions WHERE name = 'Designer UX/UI')),
((SELECT id FROM t_mbti_types WHERE code = 'ISFP'),
(SELECT id FROM t_professions WHERE name = 'Développeur indépendant'));

INSERT INTO t_matches(mbti_type_id, profession_id)VALUES   
((SELECT id FROM t_mbti_types WHERE code = 'ESTP'),
(SELECT id FROM t_professions WHERE name = 'Trader')),
((SELECT id FROM t_mbti_types WHERE code = 'ESTP'),
(SELECT id FROM t_professions WHERE name = 'Entrepreneur')),
((SELECT id FROM t_mbti_types WHERE code = 'ESTP'),
(SELECT id FROM t_professions WHERE name = 'Agent immobilier')),
((SELECT id FROM t_mbti_types WHERE code = 'ESTP'),
(SELECT id FROM t_professions WHERE name = 'Responsable des ventes')),
((SELECT id FROM t_mbti_types WHERE code = 'ESTP'),
(SELECT id FROM t_professions WHERE name = 'Négociateur en affaires')),
((SELECT id FROM t_mbti_types WHERE code = 'ESTP'),
(SELECT id FROM t_professions WHERE name = 'Consultant en marketing digital')),
((SELECT id FROM t_mbti_types WHERE code = 'ESTP'),
(SELECT id FROM t_professions WHERE name = 'Ingénieur commercial')),
((SELECT id FROM t_mbti_types WHERE code = 'ESTP'),
(SELECT id FROM t_professions WHERE name = 'Spécialiste en communication de crise')),
((SELECT id FROM t_mbti_types WHERE code = 'ESTP'),
(SELECT id FROM t_professions WHERE name = 'Animateur télé')),
((SELECT id FROM t_mbti_types WHERE code = 'ESTP'),
(SELECT id FROM t_professions WHERE name = 'Agent sportif')),
((SELECT id FROM t_mbti_types WHERE code = 'ESTP'),
(SELECT id FROM t_professions WHERE name = 'Consultant en gestion de crise')),
((SELECT id FROM t_mbti_types WHERE code = 'ESTP'),
(SELECT id FROM t_professions WHERE name = 'Spécialiste en relations publiques')),
((SELECT id FROM t_mbti_types WHERE code = 'ESTP'),
(SELECT id FROM t_professions WHERE name = 'Conférencier en entrepreneuriat')),
((SELECT id FROM t_mbti_types WHERE code = 'ESTP'),
(SELECT id FROM t_professions WHERE name = 'Responsable événementiel')),
((SELECT id FROM t_mbti_types WHERE code = 'ESTP'),
(SELECT id FROM t_professions WHERE name = 'Formateur en techniques de vente'));

INSERT INTO t_matches(mbti_type_id, profession_id)VALUES   
((SELECT id FROM t_mbti_types WHERE code = 'ESFP'),
(SELECT id FROM t_professions WHERE name = 'Acteur')),
((SELECT id FROM t_mbti_types WHERE code = 'ESFP'),
(SELECT id FROM t_professions WHERE name = 'Chanteur')),
((SELECT id FROM t_mbti_types WHERE code = 'ESFP'),
(SELECT id FROM t_professions WHERE name = 'Humoriste')),
((SELECT id FROM t_mbti_types WHERE code = 'ESFP'),
(SELECT id FROM t_professions WHERE name = 'Musicien')),
((SELECT id FROM t_mbti_types WHERE code = 'ESFP'),
(SELECT id FROM t_professions WHERE name = 'Coach sportif')),
((SELECT id FROM t_mbti_types WHERE code = 'ESFP'),
(SELECT id FROM t_professions WHERE name = 'Animateur radio')),
((SELECT id FROM t_mbti_types WHERE code = 'ESFP'),
(SELECT id FROM t_professions WHERE name = 'Influenceur digital')),
((SELECT id FROM t_mbti_types WHERE code = 'ESFP'),
(SELECT id FROM t_professions WHERE name = 'Conférencier motivationnel')),
((SELECT id FROM t_mbti_types WHERE code = 'ESFP'),
(SELECT id FROM t_professions WHERE name = 'Maître de cérémonie')),
((SELECT id FROM t_mbti_types WHERE code = 'ESFP'),
(SELECT id FROM t_professions WHERE name = 'Responsable de casting')),
((SELECT id FROM t_mbti_types WHERE code = 'ESFP'),
(SELECT id FROM t_professions WHERE name = 'Spécialiste en organisation d’événements')),
((SELECT id FROM t_mbti_types WHERE code = 'ESFP'),
(SELECT id FROM t_professions WHERE name = 'Danseur professionnel')),
((SELECT id FROM t_mbti_types WHERE code = 'ESFP'),
(SELECT id FROM t_professions WHERE name = 'Consultant en image')),
((SELECT id FROM t_mbti_types WHERE code = 'ESFP'),
(SELECT id FROM t_professions WHERE name = 'Responsable relations presse')),
((SELECT id FROM t_mbti_types WHERE code = 'ESFP'),
(SELECT id FROM t_professions WHERE name = 'Animateur de festivals'));

SELECT * FROM t_matches tm ;